Remove audio/video feature from editor when requested for Zimbra
entcore/infra-front pull request #59
Opened 2020-09-18 08:48 UTC by sjollois

When need to remove audio/video feature from editor when requested for Zimbra module because this features don't work on this module in the mails

2020-09-18 09:19 UTC, rdjedjig commented
Bonjour @sjollois,

J'ai 2 remarques a chaud : 

* Il y a du reformatage de code dans le commit. Cela gêne beaucoup la lisibilité. Il faut sortir le reformatage (s'il est utile) dans un commit séparé
* Je suis surpris qu'on bride l'intégration multimédia dans la messagerie ENT.  Je vais me renseigner auprès de mon équipe Produit.

2020-09-18 09:49 UTC, lpotcgi commented
Bonjour,

L'intégration sous forme d'iFrame d'une video dans un mail est interdite pour des raisons de sécurité.
De plus les URL de la vidéo ou de l'audio pointant dans workspace en chemin relatif.

Ces intégrations sont  inutilisable dans les mails reçus dans le mode expert ou en dehors.

En attendant de trouver une solution pérenne on souhaite désactiver ces fonctions d'intégration audio vidéo pour **zimbra seulement.**

Le but de cette pull request est de permettre cette désactivation sur demande depuis les modules, sans intervention sur les modules déjà existants et utilisant ces fonctionnalités,

2020-11-27 10:55 UTC, nabil-mansouri requested changes
Il faudrait réécrire le if pour que ce soit plus lisible (et isolé les app concerné dans la condition).
Vu avec samuel ca serait quelque chose genre:
function addTemplate(){
                var optionElement = $('<div></div>');
                optionElement.addClass('option');
                optionElement.addClass(optionName);
                instance.element.find('editor-toolbar').append(optionElement);
                var optionScope = instance.scope.$new();
                var optionResult = option.run(instance);
                if (optionResult.template) {
                    optionElement.html(instance.compile(optionResult.template)(optionScope));
                    optionResult.link(optionScope, optionElement, instance.attributes);
                }
                if (optionResult.templateUrl) {
                    http().get(optionResult.templateUrl).done(function (content) {
                        optionElement.html(instance.compile(content)(optionScope));
                        optionResult.link(optionScope, optionElement, instance.attributes);
                    }.bind(this));
                }
}
var optionName = option.name.replace(/([A-Z])/g, "-$1").toLowerCase();
if(optionName == "sound"){
     if(!instance.hiddenShareSoundCode) addTemplate();
}else if(optionName == "embed"){
     if(!instance.hiddenShareVideoCode)  addTemplate();
}else {
      addTemplate();
}

2020-11-27 11:18 UTC, nabil-mansouri approved these changes

2020-11-27 11:18 UTC, merged