Fix: #WB-2026  Change display to firstname for welcome key i18n
entcore/infra-front pull request #71
Opened 2023-10-19 13:44 UTC by Romu-C

2023-10-20 07:53 UTC, ccreusat requested changes

2023-10-20 07:53 UTC, ccreusat commented on src/ts/theme.ts
> +                    console.log({legacy});
A supprimer

2023-10-20 08:07 UTC, jcbe-ode requested changes
Sur entcore et infra-front, je préfèrerais que le formatage auto soit désactivé.

    on l'activera dans entcore lors de la migration front.
    infra-front restera en l'état et sera dépréciée.

2023-10-31 09:32 UTC, Romu-C commented on src/ts/theme.ts
> +                    console.log({legacy});
Done

2023-10-31 09:33 UTC, Romu-C commented
> Sur entcore et infra-front, je préfèrerais que le formatage auto soit désactivé.
> 
> ```
> on l'activera dans entcore lors de la migration front.
> infra-front restera en l'état et sera dépréciée.
> ```

Je viens de retirer le formatage des fichiers changé

2023-11-10 14:45 UTC, merged